alertmanager:
  enabled: true

grafana:
  image:
    tag: 8.5.15
  admin:
    existingSecret: grafana-admin-password
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Editor
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder:
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      zeebe:
        url: https://raw.githubusercontent.com/camunda/zeebe/main/monitor/grafana/zeebe.json
      zeebe-overview:
        url: https://raw.githubusercontent.com/camunda/zeebe/main/monitor/grafana/zeebe-overview.json
  persistence:
    enabled: true
    storageClassName: ssd
  sidecar:
    dashboards:
      searchNamespace: ALL

prometheusOperator:
  admissionWebhooks:
    patch:
      image:
        # the default image in newer chart versions, and required for k8s 1.22
        repository: k8s.gcr.io/ingress-nginx/kube-webhook-certgen
        tag: v1.2.0

thanosRuler:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ssd
          selector:
            matchLabels:
              app: prometheus
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Gi
