apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-starter
  labels:
    app: simple-starter
spec:
  selector:
    matchLabels:
      app: simple-starter
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-starter
    spec:
      containers:
        - name: simple
          image: gcr.io/zeebe-io/starter:SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=default-zeebe-gateway:26500
                -Dapp.starter.rate=100
                -Dzeebe.client.requestTimeout=62000
                -XX:+HeapDumpOnOutOfMemoryError
                -Dapp.starter.bpmnXmlPath=bpmn/simpleProcess.bpmn
                -Dapp.starter.processId=simpleProcess
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: simple-starter-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: zeebe-cluster
  name: simple-starter
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9600
      protocol: TCP
      targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: simple-starter
  sessionAffinity: None
  type: ClusterIP
