apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
        metrics: gmp
    spec:
      containers:
        - name: worker
          image: gcr.io/zeebe-io/worker:SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=default-zeebe-gateway:26500
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity=60
                -Dapp.worker.pollingDelay=1ms
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: worker-config
                optional: true
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: zeebe-cluster
  name: worker
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9600
      protocol: TCP
      targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: { }
