name: Benchmark
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Specifies the name of the benchmark'
        required: true
      ref:
        description: 'Specifies the ref (e.g. main or a commit sha) to benchmark'
        default: 'main'
        required: false
      cluster:
        description: 'Specifies which cluster to deploy the benchmark on'
        default: 'zeebe-cluster'
        required: false
      cluster-region:
        description: 'Specifies the cluster region. Needed to retrieve cluster credentials'
        default: europe-west1-b
        required: false
      benchmark-load:
        description: 'Specifies which benchmark components to deploy. `starter`, `timer` and `publisher` can be assigned with the rate at which they publish. Allows arbitary helm arguments, like --set starter.rate=100'
        required: false
  workflow_call:
    inputs:
      name:
        description: 'Specifies the name of the benchmark'
        type: string
        required: true
      ref:
        description: 'Specifies the ref (e.g. main or a commit sha) to benchmark'
        default: 'main'
        type: string
        required: false
      cluster:
        description: 'Specifies which cluster to deploy the benchmark on'
        default: 'zeebe-cluster'
        type: string
        required: false
      cluster-region:
        description: 'Specifies the cluster region. Needed to retrieve cluster credentials'
        default: europe-west1-b
        type: string
        required: false
      benchmark-load:
        description: 'Specifies which benchmark components to deploy. `starter`, `timer` and `publisher` can be assigned with the rate at which they publish. Allows arbitary helm arguments, like --set starter.rate=100'
        type: string
        required: false
jobs:
  build-zeebe-image:
    name: Build zeebe image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      image-tag: ${{ steps.image-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: zeebe-io
          install_components: gke-gcloud-auth-plugin, kubectl
      - run: gcloud auth configure-docker
      - uses: ./.github/actions/setup-zeebe
        with:
          maven-cache: 'true'
      - name: Get image tag
        id: image-tag
        run: |
          echo "image-tag=${{ inputs.name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/build-zeebe
        id: build-zeebe
        with:
          maven-extra-args: -T1C
      - uses: ./.github/actions/build-docker
        with:
          repository: gcr.io/zeebe-io/zeebe
          version: ${{ steps.image-tag.outputs.image-tag }}
          push: true
          distball: ${{ steps.build-zeebe.outputs.distball }}
  deploy-benchmark-cluster:
    name: Deploy benchmark cluster
    needs:
      - build-zeebe-image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: zeebe-io
          install_components: gke-gcloud-auth-plugin, kubectl
      - uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          cluster_name: ${{ inputs.cluster }}
          location: ${{ inputs.cluster-region }}
      - uses: azure/setup-helm@v3
      - name: Add camunda helm repo
        run: |
          helm repo add camunda https://helm.camunda.io
          helm repo update
      - uses: actions/checkout@v3
        with:
          repository: zeebe-io/benchmark-helm
          path: benchmark-helm
      - name: Helm dependency build
        working-directory: benchmark-helm/zeebe-benchmark
        run: |
          helm dependency build
      - name: Helm install
        working-directory: benchmark-helm/zeebe-benchmark
        run: >
          helm upgrade --install ${{ inputs.name }} .
          --namespace ${{ inputs.name }}
          --create-namespace
          --set camunda-platform.zeebe.image.repository=gcr.io/zeebe-io/zeebe
          --set camunda-platform.zeebe.image.tag=${{ needs.build-zeebe-image.outputs.image-tag }}
          --set camunda-platform.zeebe-gateway.image.repository=gcr.io/zeebe-io/zeebe
          --set camunda-platform.zeebe-gateway.image.tag=${{ needs.build-zeebe-image.outputs.image-tag }}
          ${{ inputs.benchmark-load }}
