name: Weekly medic benchmark
on:
  workflow_dispatch: { }
  schedule:
    # Runs at 1am every monday https://crontab.guru/#0_1_*_*_1
    - cron: 0 1 * * 1

jobs:
  delete-old-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: zeebe-io
          install_components: gke-gcloud-auth-plugin, kubectl
      - uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          cluster_name: zeebe-cluster
          location: europe-west1-b
      - name: Collect benchmark data
        id: data
        run: |
          # Get all namespaces, filter for medic benchmarks and select the oldest one
          echo "normal=$(kubectl get ns -o name | grep -E namespace/medic-cw-[0-9]+-[a-z0-9]+-benchmark$ | sort -V | head -n1)" >> $GITHUB_OUTPUT
      - name: Delete benchmarks
        run: |
          kubectl delete ${{ steps.data.outputs.normal }}
          kubectl delete ${{ steps.data.outputs.normal }}-mixed
          kubectl delete ${{ steps.data.outputs.normal }}-latency
  benchmark-data:
    name: Collect benchmark data
    runs-on: ubuntu-latest
    outputs:
      full-ref: ${{ steps.data.outputs.full-ref }}
      ref: ${{ steps.data.outputs.ref }}
      cw: ${{ steps.data.outputs.cw }}
    steps:
      - uses: actions/checkout@v3
      - name: Collect benchmark data
        id: data
        run: |
          echo "full-ref"=$(git rev-parse HEAD) >> $GITHUB_OUTPUT
          echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "cw=$(date +%V)" >> $GITHUB_OUTPUT

  setup-normal-benchmark:
    name: Setup normal benchmark
    needs:
      - benchmark-data
      - delete-old-benchmarks
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      name: medic-cw-${{ needs.benchmark-data.outputs.cw }}-${{ needs.benchmark-data.outputs.ref }}-benchmark
      cluster: zeebe-cluster
      cluster-region: europe-west1-b
      ref: ${{ needs.benchmark-data.outputs.full-ref }}
  setup-mixed-benchmark:
    name: Setup mixed benchmark
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    needs:
      - benchmark-data
      - delete-old-benchmarks
    with:
      name: medic-cw-${{ needs.benchmark-data.outputs.cw }}-${{ needs.benchmark-data.outputs.ref }}-benchmark-mixed
      cluster: zeebe-cluster
      cluster-region: europe-west1-b
      ref: ${{ needs.benchmark-data.outputs.full-ref }}
      benchmark-load: >
        --set starter.rate=25
        --set timer.replicas=1
        --set timer.rate=25
        --set publisher.replica=1
        --set publisher.rate=25
  setup-latency-benchmark:
    name: Setup latency benchmark
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    needs:
      - benchmark-data
      - delete-old-benchmarks
    with:
      name: medic-cw-${{ needs.benchmark-data.outputs.cw }}-${{ needs.benchmark-data.outputs.ref }}-benchmark-latency
      cluster: zeebe-cluster
      cluster-region: europe-west1-b
      ref: ${{ needs.benchmark-data.outputs.full-ref }}
      benchmark-load: >
        --set starter.rate=1
        --set worker.replicas=1
