name: Release Dry Run from main
on:
  workflow_dispatch: { }
  schedule:
    # Runs at 01:00 every week day; see this link for more: https://crontab.guru/#0_1_*_*_1-5
    - cron: '0 1 * * 1-5'

jobs:
  dry-run-release:
    name: "${{ matrix.version }} from main"
    uses: ./.github/workflows/release.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        version: [ 0.8.2, 0.8.2-alpha1 ]
        include:
          - version: 0.8.2
            latest: true
          - version: 0.8.2-alpha1
            latest: false
    with:
      releaseBranch: main
      releaseVersion: ${{ matrix.version }}
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: ${{ matrix.latest }}
      dryRun: true
  notify-if-failed:
    name: Send slack notification on failure
    runs-on: ubuntu-latest
    needs: [ dry-run-release ]
    if: ${{ failure() }}
    steps:
      - id: slack-notify
        name: Send slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": ":alarm: *Release Dry Run* from `main` failed! :alarm:\n",
             	"blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":alarm: *Release Dry Run* from `main` failed! :alarm:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the related workflow execution: https://github.com/camunda/zeebe/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
